#!/usr/bin/env python3
"""Build the isolated, single-file owner-grant verifier."""

import argparse
import base64
import json
import marshal
from pathlib import Path
import sys
import zlib


ROOT = Path(__file__).resolve().parents[1]
MODULES = (
    "envelope",
    "ed25519_pure",
    "scopes",
    "anchor",
    "quote",
    "verify",
    "cli",
)


def _pack(data: bytes) -> str:
    return base64.b85encode(zlib.compress(data, 9)).decode("ascii")


def build(output: Path) -> Path:
    sources = {
        name: (ROOT / "hermes_owner_grant" / (name + ".py")).read_text(encoding="utf-8")
        for name in MODULES
    }
    catalog = json.loads(
        (ROOT / "hermes_owner_grant" / "scopes.json").read_text(encoding="utf-8")
    )
    code_objects = {
        name: _pack(marshal.dumps(compile(source, "<owner-grant:%s>" % name, "exec")))
        for name, source in sources.items()
    }
    packed_sources = {
        name: _pack(source.encode("utf-8")) for name, source in sources.items()
    }
    lines = [
        "#!/usr/bin/env python3",
        '"""Generated by scripts/build_owner_verifier.py; do not edit."""',
        "import sys as _sys",
        "import types as _types",
        "import marshal as _marshal",
        "import base64 as _base64",
        "import zlib as _zlib",
        "_BUILD_VERSION = " + repr(sys.version_info[:2]),
        "_BUILD_IMPLEMENTATION = " + repr(sys.implementation.name),
        "_PACKAGE = 'hermes_owner_grant'",
        "_package = _types.ModuleType(_PACKAGE)",
        "_package.__path__ = []",
        "_package.__package__ = _PACKAGE",
        "_sys.modules[_PACKAGE] = _package",
        "_SOURCES = " + repr(packed_sources),
        "_CODE = " + repr(code_objects),
        "_CATALOG = "
        + repr(json.dumps(catalog, sort_keys=True, separators=(",", ":"))),
        "for _name in " + repr(MODULES) + ":",
        "    _fullname = _PACKAGE + '.' + _name",
        "    _module = _types.ModuleType(_fullname)",
        "    _module.__file__ = __file__ + ':' + _name",
        "    _module.__package__ = _PACKAGE",
        "    if _name == 'scopes':",
        "        _module._BUNDLED_CATALOG_JSON = _CATALOG",
        "    _sys.modules[_fullname] = _module",
        "    setattr(_package, _name, _module)",
        "    if _sys.version_info[:2] == _BUILD_VERSION and _sys.implementation.name == _BUILD_IMPLEMENTATION:",
        "        _packed = _base64.b85decode(_CODE[_name].encode('ascii'))",
        "        _module_code = _marshal.loads(_zlib.decompress(_packed))",
        "    else:",
        "        _packed = _base64.b85decode(_SOURCES[_name].encode('ascii'))",
        "        _source = _zlib.decompress(_packed).decode('utf-8')",
        "        _module_code = compile(_source, _module.__file__, 'exec')",
        "    exec(_module_code, _module.__dict__)",
        "if __name__ == '__main__':",
        "    raise SystemExit(_sys.modules[_PACKAGE + '.cli'].main())",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    output.chmod(0o755)
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="path for the standalone verifier")
    args = parser.parse_args()
    print(build(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
